export const SET_NEXT_STEP = "APP/SET_CURRENT_STEP";
export const SET_PREV_STEP = "APP/SET_PREV_STEP";

export const SET_STEP_ONE = "APP/SET_STEP_ONE";
export const SET_STEP_TWO = "APP/SET_STEP_TWO";
export const SET_STEP_THREE = "APP/SET_STEP_THREE";
export const SET_STEP_FOUR = "APP/SET_STEP_FOUR";

export const SET_ERROR = "APP/SET_ERROR";
export const SET_CHOOSEN_VALUE = "APP/SET_CHOOSEN_VALUE";
